### ISSUE TITLE
Configuration issue ?

### ISSUE THREAD

**Issue by vincegre** [koying/jellyfin_ha#13]
Hi

Trying to use that custom integration but a little confused :( I have installed the integration in hacs, then restarted hassio then i go into Integrations but no Jellyfin shows up in list of integrations ! How do you configure it ? Missing something obvious I guess but can't find any doc about setup :(

Thanks

Vincèn

**Comment by BelgarionNL** [comment]
same!

**Comment by vincegre** [comment]
> same!

Well after multiple restarts of HA and Hassio host, Jellyfin integration finally showed up in HA and then I colud easily setup it and now I have status properly reported of all players ;)

![Screenshot_20210913_094844](https://user-images.githubusercontent.com/3164888/133044568-5714eb36-1689-4fe5-a186-f916ae3dd749.png)
