### ISSUE TITLE
Active Devices

### ISSUE THREAD

**Issue by gurg1e** [koying/jellyfin_ha#15]
This would be great if it pulled down the active devices connected to Jellyfin, so HA is able to show when people are watching things. Thanks!

**Comment by koying** [comment]
One media player entity is created for each device recognized by Jellyfin.
They are on if active, and off if inactive

**Comment by gurg1e** [comment]
Right i see, thanks. Are you able to help with a jinja template to pull the current number, and list of active devices?

**Comment by koying** [comment]
See, e.g., https://community.home-assistant.io/t/how-to-enumerate-entities-belonging-to-an-integration/343748/6?u=koying

**Comment by gurg1e** [comment]
Wow great link thanks. But it was only able to find the Jellyfin sensor and not the media players.
