### ISSUE TITLE
GUI install bug 

### ISSUE THREAD

**Issue by JulienFloris** [koying/jellyfin_ha#17]
I don't have a password setup JellyFin. But the Install GUI does require one. 
Can this GUI requirement be removed or is there an reason this is required? 

![image](https://user-images.githubusercontent.com/20380255/139098346-3944e9a2-a1cf-4d25-ad43-0d37b08d2dbb.png)

Is it this line of code?
https://github.com/koying/jellyfin_ha/blob/dc7c37dde1e222d3cb15166b134bfed066617139/custom_components/jellyfin/config_flow.py#L64

**Comment by JulienFloris** [comment]
i tried to edit just this line but that give's an error. after the setup of the integration.

**Comment by lichenophile** [comment]
Looks like there's an issue with blank passwords still if you reconfigure the integration. 
For now, removing the integration and re-adding it appears to allow for blank password.
