### ISSUE TITLE
Integration not available after installing in HACS

### ISSUE THREAD

**Issue by Potplanty** [koying/jellyfin_ha#20]
Just went to install this today and it downloads and installs in HACS just fine. Reboot the HA server multiple times but the Jellyfin integration never shows up to add. There's nothing at all available in the standard integration page via HA to install this.

**Comment by koying** [comment]
Works for me...

![image](https://user-images.githubusercontent.com/164740/143910133-746d6d19-9aa1-4808-b1b9-3e908d204fde.png)

![image](https://user-images.githubusercontent.com/164740/143910176-6a7861c8-d277-470d-b51c-576fc58ccd11.png)

**Comment by Potplanty** [comment]
Dunno what changed but it's working now. Wasn't the only user with this issue but seems it's working. Maybe the repo was temporarily down.
