### ISSUE TITLE
Jellyfin users without password

### ISSUE THREAD

**Issue by GyroLand** [koying/jellyfin_ha#7]
My user in Jellyfin has no password, but it is not possible to add the integration without a password as it is a mandatory field.
Would it be possible to add passwordless users? Maybe using the API key?

**Comment by tylerszabo** [comment]
Instead of attempting to give the credentials as a particular user you can create a user for Home Assistant and allow that user to manage the screens including those logged in as other users.

**Comment by GyroLand** [comment]
This actually worked, thanks for the advice!
